#! /bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &
picom &

~/.config/bspwm/reloadablerc

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
