#! /bin/sh

~/.screenlayout/def.sh
nitrogen --restore
setxkbmap -option 'caps:super'
sxhkd -c ~/.config/bspwm/sxhkdrc &
polybar &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
