#! /bin/sh

export DESKTOP_SESSION=bspwm

xset s 300 5
xss-lock -n /usr/libexec/xsecurelock/dimmer -l -- xsecurelock &
sxhkd -c ~/.config/bspwm/sxhkdrc &
picom &

~/.config/bspwm/reloadablerc

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# consistent placement
bspc rule -a Slack desktop='^8' follow=on
bspc rule -a Spotify desktop='^9' follow=on

# settings float
bspc rule -a Arandr state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating
