#! /bin/sh

autorandr --change

# detect screens

main=$(xrandr | grep primary | awk '{print $1}')
second=$(xrandr | grep " connected" | grep -v primary | awk '{print $1}')
echo $main $second

all_mons=$(xrandr --query | grep " connected" | cut -d" " -f1)
mon_count=$(xrandr --query | grep " connected" | wc -l)

# polybar

if type "xrandr"; then
    for m in $all_mons; do
        MONITOR=$m polybar --reload example &
    done
else
    polybar --reload example &
fi

# monitors

if [[ $mon_count == 1 ]]
then
    bspc monitor $builtin_mon -d 1 2 3 4 5 6 7 8 9 0
else
    bspc wm --reorder-monitors $main $second
    bspc monitor $(bspc query -M | sed -n 1p) -d 1 2 3 4 5 6 7
    bspc monitor $(bspc query -M | sed -n 2p) -d 8 9 0
fi

