#! /bin/sh


setxkbmap -option 'caps:super'
autorandr --change

# detect screens

main=$(xrandr | grep primary | awk '{print $1}')
second=$(xrandr | grep " connected" | grep -v primary | awk '{print $1}')

all_mons=$(xrandr --query | grep " connected" | cut -d" " -f1)
mon_count=$(xrandr --query | grep " connected" | wc -l)

# polybar

# kill existing

for pid in $(ps aux | grep "polybar --reload" | grep -v grep | awk '{print $2}'); do
    kill $pid
done

if type "xrandr"; then
    i=0
    for m in $all_mons; do
        nitrogen --set-zoom-fill --head=$i ~/dev/dotfiles/bg.jpg
        MONITOR=$m polybar --reload jl &
        ((i=i+1))
    done
else
    nitrogen --set-zoom-fill ~/dev/dotfiles/bg.jpg
    polybar --reload example &
fi

# workspaces

primary_spaces="1 2 3 4 5 6 7"
secondary_spaces="8 9 0"

# monitors

if [[ $mon_count == 1 ]]
then
    bspc monitor $main -d $primary_spaces $secondary_spaces
else
    bspc wm --reorder-monitors $main $second
    bspc monitor $(bspc query -M | sed -n 1p) -d $primary_spaces
    bspc monitor $(bspc query -M | sed -n 2p) -d $secondary_spaces
fi

