#! /bin/bash
#
# Thanks: https://gist.github.com/miyl/40cdf1a66b360ad8ec0b19e2ffa56194?permalink_comment_id=4249357#gistcomment-4249357
# usage:
#   change the default sink = rofi-pa-default sink
#   change the default source = rofi-pa-default source

pactl set-default-${1} $(pactl list short ${1}s | awk '{print $2}' | rofi -dmenu)
